## The functions makeCacheMatrix and cacheSolve provide a way to find the inverse of a square (nxn) matrix 
## The inverse matrix is cached so that subsequent calls to the function require no computation.
## the super assignment operator <<- is used to make variables globally accessable
##
## The function makeCacheMatrix takes a nxn matrix as an argument and returns a list vector that provides the storage location of the matrix 
## and functions for retriveing that matrix and storinging and retrieving the inverse when it has been Calculated
##
## The function cacheSolve takes a list generated by makeCacheMatrix and retreives the inverse matrix - If is exists it returns the inverse with out calculation
## If it does not exist it retrives the Matrix to be inverted and uses the function solve to calc the inverse and then store it in the globally readable variable m

## makeCacheMatrix(x=matrix()) Stores the matrix x in globablly accesable space, sets the inverse result to NULL and 
## returns a list of the functions and environements for retrieving and storing x and and retrieving and storing M the inverse matrix

makeCacheMatrix <- function(x = matrix()) {
      m<-NULL ##initializes solution matrix to NULL
      set<-function(y){
            x<<-y      ##super assignment of the input matrix to variable x
            m<<-NULL   ##super assignment of NULL to variable m - m will contain the inverse of x after solving.
                       ##set to null for new a matrix
      }
      get<-function() x ##this function retrives the input stored matrix x
      setmatrix<-function(m_inverse) m<<- m_inverse ##funtion super assigns the solved inverse matrix in m 
      getmatrix<-function() m ##retrieves the super assigned inverse matrix (NULL or solved)
      list(set=set, get=get,
           setmatrix=setmatrix,
           getmatrix=getmatrix
           ) ##returnthe functions in a list
}



## cacheSolve <- function(x=list(),..) calculates the inverse of the  matrix defined in the List created by makeCacheMatrix
## If the inverse already exists then the store value m is returned using the function getmatrix. Else the stored matrix X is retrived
## using x$Get() and its inverse is calc'd using solve and stored in m using x$setmatrix

cacheSolve <- function(x=list(),...) {
      m<-x$getmatrix() ##get stored inverse matrix (m) if not NULL then this matrix inverse has been solved
      if(!is.null(m)){
            message("getting cached data")
            return(m)
      }
      matrix<-x$get()  ##If stored m was NULL then get stored Matrix to be solved (x)
      m<-solve(matrix, ...)
      x$setmatrix(m) ##Causes inverse to be super assigned to m 
      m
}
